# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_setup.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(581, 464)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.curr_stamps_list = QtWidgets.QListWidget(self.centralwidget)
        self.curr_stamps_list.setGeometry(QtCore.QRect(10, 50, 181, 371))
        self.curr_stamps_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.curr_stamps_list.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.curr_stamps_list.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.curr_stamps_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.curr_stamps_list.setProperty("isWrapping", True)
        self.curr_stamps_list.setWordWrap(True)
        self.curr_stamps_list.setSelectionRectVisible(True)
        self.curr_stamps_list.setObjectName("curr_stamps_list")
        self.curr_stamps_label = QtWidgets.QLabel(self.centralwidget)
        self.curr_stamps_label.setGeometry(QtCore.QRect(10, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.curr_stamps_label.setFont(font)
        self.curr_stamps_label.setObjectName("curr_stamps_label")
        self.amount_stamps_label = QtWidgets.QLabel(self.centralwidget)
        self.amount_stamps_label.setGeometry(QtCore.QRect(230, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.amount_stamps_label.setFont(font)
        self.amount_stamps_label.setObjectName("amount_stamps_label")
        self.amount_stamps_list = QtWidgets.QListWidget(self.centralwidget)
        self.amount_stamps_list.setGeometry(QtCore.QRect(230, 50, 91, 371))
        self.amount_stamps_list.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.amount_stamps_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.amount_stamps_list.setProperty("isWrapping", True)
        self.amount_stamps_list.setUniformItemSizes(False)
        self.amount_stamps_list.setWordWrap(True)
        self.amount_stamps_list.setSelectionRectVisible(False)
        self.amount_stamps_list.setObjectName("amount_stamps_list")
        self.btn_frame = QtWidgets.QFrame(self.centralwidget)
        self.btn_frame.setGeometry(QtCore.QRect(360, 50, 211, 371))
        self.btn_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.btn_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.btn_frame.setObjectName("btn_frame")
        self.rmv_selected_btn = QtWidgets.QToolButton(self.btn_frame)
        self.rmv_selected_btn.setGeometry(QtCore.QRect(10, 270, 191, 31))
        self.rmv_selected_btn.setObjectName("rmv_selected_btn")
        self.add_new_stamp_btn = QtWidgets.QToolButton(self.btn_frame)
        self.add_new_stamp_btn.setGeometry(QtCore.QRect(10, 160, 191, 31))
        self.add_new_stamp_btn.setObjectName("add_new_stamp_btn")
        self.new_stamp_name_line_edit = QtWidgets.QLineEdit(self.btn_frame)
        self.new_stamp_name_line_edit.setGeometry(QtCore.QRect(10, 30, 191, 20))
        self.new_stamp_name_line_edit.setObjectName("new_stamp_name_line_edit")
        self.new_stamp_amount_line_edit = QtWidgets.QLineEdit(self.btn_frame)
        self.new_stamp_amount_line_edit.setGeometry(QtCore.QRect(10, 80, 191, 21))
        self.new_stamp_amount_line_edit.setObjectName("new_stamp_amount_line_edit")
        self.new_stamp_name_label = QtWidgets.QLabel(self.btn_frame)
        self.new_stamp_name_label.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.new_stamp_name_label.setFont(font)
        self.new_stamp_name_label.setObjectName("new_stamp_name_label")
        self.new_stamp_amount_label = QtWidgets.QLabel(self.btn_frame)
        self.new_stamp_amount_label.setGeometry(QtCore.QRect(10, 60, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.new_stamp_amount_label.setFont(font)
        self.new_stamp_amount_label.setObjectName("new_stamp_amount_label")
        self.horizontal_line_1 = QtWidgets.QFrame(self.btn_frame)
        self.horizontal_line_1.setGeometry(QtCore.QRect(-3, 190, 211, 20))
        self.horizontal_line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontal_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontal_line_1.setObjectName("horizontal_line_1")
        self.rmv_stamp_amount_label = QtWidgets.QLabel(self.btn_frame)
        self.rmv_stamp_amount_label.setGeometry(QtCore.QRect(10, 210, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rmv_stamp_amount_label.setFont(font)
        self.rmv_stamp_amount_label.setObjectName("rmv_stamp_amount_label")
        self.rmv_stamp_amount_line_edit = QtWidgets.QLineEdit(self.btn_frame)
        self.rmv_stamp_amount_line_edit.setGeometry(QtCore.QRect(10, 230, 191, 31))
        self.rmv_stamp_amount_line_edit.setObjectName("rmv_stamp_amount_line_edit")
        self.save_changes_btn = QtWidgets.QToolButton(self.btn_frame)
        self.save_changes_btn.setGeometry(QtCore.QRect(10, 330, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save_changes_btn.setFont(font)
        self.save_changes_btn.setObjectName("save_changes_btn")
        self.horizontal_line_2 = QtWidgets.QFrame(self.btn_frame)
        self.horizontal_line_2.setGeometry(QtCore.QRect(0, 310, 211, 20))
        self.horizontal_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontal_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontal_line_2.setObjectName("horizontal_line_2")
        self.new_stamp_value_label = QtWidgets.QLabel(self.btn_frame)
        self.new_stamp_value_label.setGeometry(QtCore.QRect(10, 110, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.new_stamp_value_label.setFont(font)
        self.new_stamp_value_label.setObjectName("new_stamp_value_label")
        self.new_stamp_value_line_edit = QtWidgets.QLineEdit(self.btn_frame)
        self.new_stamp_value_line_edit.setGeometry(QtCore.QRect(10, 130, 191, 21))
        self.new_stamp_value_line_edit.setObjectName("new_stamp_value_line_edit")
        self.tools_label = QtWidgets.QLabel(self.centralwidget)
        self.tools_label.setGeometry(QtCore.QRect(360, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tools_label.setFont(font)
        self.tools_label.setObjectName("tools_label")
        self.veritcal_line_1 = QtWidgets.QFrame(self.centralwidget)
        self.veritcal_line_1.setGeometry(QtCore.QRect(200, 0, 20, 421))
        self.veritcal_line_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.veritcal_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.veritcal_line_1.setObjectName("veritcal_line_1")
        self.veritcal_line_2 = QtWidgets.QFrame(self.centralwidget)
        self.veritcal_line_2.setGeometry(QtCore.QRect(330, 0, 20, 421))
        self.veritcal_line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.veritcal_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.veritcal_line_2.setObjectName("veritcal_line_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 581, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stamp Calculator Config"))
        self.curr_stamps_label.setText(_translate("MainWindow", "Current Stamps"))
        self.amount_stamps_label.setText(_translate("MainWindow", "Amount"))
        self.rmv_selected_btn.setText(_translate("MainWindow", "Remove amount from selected stamp"))
        self.add_new_stamp_btn.setText(_translate("MainWindow", "Add Stamp"))
        self.new_stamp_name_label.setText(_translate("MainWindow", "New stamp name:"))
        self.new_stamp_amount_label.setText(_translate("MainWindow", "New stamp amount:"))
        self.rmv_stamp_amount_label.setText(_translate("MainWindow", "Remove amount from selected:"))
        self.save_changes_btn.setText(_translate("MainWindow", "SAVE CHANGES"))
        self.new_stamp_value_label.setText(_translate("MainWindow", "New stamp value:"))
        self.tools_label.setText(_translate("MainWindow", "Tools"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

