# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stamp_calc.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 472)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.small_parcel_label = QtWidgets.QLabel(self.centralwidget)
        self.small_parcel_label.setGeometry(QtCore.QRect(20, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.small_parcel_label.setFont(font)
        self.small_parcel_label.setObjectName("small_parcel_label")
        self.sp_1kg = QtWidgets.QRadioButton(self.centralwidget)
        self.sp_1kg.setGeometry(QtCore.QRect(50, 50, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sp_1kg.setFont(font)
        self.sp_1kg.setObjectName("sp_1kg")
        self.sp_2kg = QtWidgets.QRadioButton(self.centralwidget)
        self.sp_2kg.setGeometry(QtCore.QRect(50, 80, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sp_2kg.setFont(font)
        self.sp_2kg.setObjectName("sp_2kg")
        self.mp_2kg = QtWidgets.QRadioButton(self.centralwidget)
        self.mp_2kg.setGeometry(QtCore.QRect(50, 190, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mp_2kg.setFont(font)
        self.mp_2kg.setObjectName("mp_2kg")
        self.mp_1kg = QtWidgets.QRadioButton(self.centralwidget)
        self.mp_1kg.setGeometry(QtCore.QRect(50, 160, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mp_1kg.setFont(font)
        self.mp_1kg.setObjectName("mp_1kg")
        self.meidum_parcel_label = QtWidgets.QLabel(self.centralwidget)
        self.meidum_parcel_label.setGeometry(QtCore.QRect(20, 120, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.meidum_parcel_label.setFont(font)
        self.meidum_parcel_label.setObjectName("meidum_parcel_label")
        self.mp_5kg = QtWidgets.QRadioButton(self.centralwidget)
        self.mp_5kg.setGeometry(QtCore.QRect(50, 220, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mp_5kg.setFont(font)
        self.mp_5kg.setObjectName("mp_5kg")
        self.mp_20kg = QtWidgets.QRadioButton(self.centralwidget)
        self.mp_20kg.setGeometry(QtCore.QRect(50, 280, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mp_20kg.setFont(font)
        self.mp_20kg.setObjectName("mp_20kg")
        self.mp_10kg = QtWidgets.QRadioButton(self.centralwidget)
        self.mp_10kg.setGeometry(QtCore.QRect(50, 250, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mp_10kg.setFont(font)
        self.mp_10kg.setObjectName("mp_10kg")
        self.calc_stamps_button = QtWidgets.QToolButton(self.centralwidget)
        self.calc_stamps_button.setGeometry(QtCore.QRect(20, 330, 111, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calc_stamps_button.setFont(font)
        self.calc_stamps_button.setObjectName("calc_stamps_button")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(170, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.result_label.setFont(font)
        self.result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.result_label.setObjectName("result_label")
        self.vertical_line_1 = QtWidgets.QFrame(self.centralwidget)
        self.vertical_line_1.setGeometry(QtCore.QRect(140, 0, 20, 431))
        self.vertical_line_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.vertical_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vertical_line_1.setObjectName("vertical_line_1")
        self.vertical_line_2 = QtWidgets.QFrame(self.centralwidget)
        self.vertical_line_2.setGeometry(QtCore.QRect(400, 0, 20, 431))
        self.vertical_line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.vertical_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vertical_line_2.setObjectName("vertical_line_2")
        self.current_stamps_label = QtWidgets.QLabel(self.centralwidget)
        self.current_stamps_label.setGeometry(QtCore.QRect(430, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.current_stamps_label.setFont(font)
        self.current_stamps_label.setAlignment(QtCore.Qt.AlignCenter)
        self.current_stamps_label.setObjectName("current_stamps_label")
        self.result_list = QtWidgets.QListWidget(self.centralwidget)
        self.result_list.setGeometry(QtCore.QRect(170, 50, 221, 381))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.result_list.setFont(font)
        self.result_list.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.result_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.result_list.setObjectName("result_list")
        self.current_stamps_list = QtWidgets.QListWidget(self.centralwidget)
        self.current_stamps_list.setGeometry(QtCore.QRect(430, 50, 221, 381))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.current_stamps_list.setFont(font)
        self.current_stamps_list.setProperty("showDropIndicator", False)
        self.current_stamps_list.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.current_stamps_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.current_stamps_list.setProperty("isWrapping", False)
        self.current_stamps_list.setWordWrap(True)
        self.current_stamps_list.setObjectName("current_stamps_list")
        self.tools_label = QtWidgets.QLabel(self.centralwidget)
        self.tools_label.setGeometry(QtCore.QRect(690, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tools_label.setFont(font)
        self.tools_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tools_label.setObjectName("tools_label")
        self.veritcal_line_2 = QtWidgets.QFrame(self.centralwidget)
        self.veritcal_line_2.setGeometry(QtCore.QRect(660, 0, 20, 431))
        self.veritcal_line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.veritcal_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.veritcal_line_2.setObjectName("veritcal_line_2")
        self.btn_frame = QtWidgets.QFrame(self.centralwidget)
        self.btn_frame.setGeometry(QtCore.QRect(690, 50, 211, 381))
        self.btn_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.btn_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.btn_frame.setObjectName("btn_frame")
        self.rmv_selected_btn = QtWidgets.QToolButton(self.btn_frame)
        self.rmv_selected_btn.setGeometry(QtCore.QRect(10, 220, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmv_selected_btn.setFont(font)
        self.rmv_selected_btn.setObjectName("rmv_selected_btn")
        self.add_new_stamp_btn = QtWidgets.QToolButton(self.btn_frame)
        self.add_new_stamp_btn.setGeometry(QtCore.QRect(10, 130, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add_new_stamp_btn.setFont(font)
        self.add_new_stamp_btn.setObjectName("add_new_stamp_btn")
        self.new_stamp_name_line_edit = QtWidgets.QLineEdit(self.btn_frame)
        self.new_stamp_name_line_edit.setGeometry(QtCore.QRect(10, 30, 191, 20))
        self.new_stamp_name_line_edit.setObjectName("new_stamp_name_line_edit")
        self.new_stamp_name_label = QtWidgets.QLabel(self.btn_frame)
        self.new_stamp_name_label.setGeometry(QtCore.QRect(10, 6, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_stamp_name_label.setFont(font)
        self.new_stamp_name_label.setObjectName("new_stamp_name_label")
        self.horizontal_line_1 = QtWidgets.QFrame(self.btn_frame)
        self.horizontal_line_1.setGeometry(QtCore.QRect(-3, 190, 211, 20))
        self.horizontal_line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontal_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontal_line_1.setObjectName("horizontal_line_1")
        self.save_changes_btn = QtWidgets.QToolButton(self.btn_frame)
        self.save_changes_btn.setGeometry(QtCore.QRect(10, 310, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save_changes_btn.setFont(font)
        self.save_changes_btn.setObjectName("save_changes_btn")
        self.horizontal_line_2 = QtWidgets.QFrame(self.btn_frame)
        self.horizontal_line_2.setGeometry(QtCore.QRect(0, 280, 211, 20))
        self.horizontal_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontal_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontal_line_2.setObjectName("horizontal_line_2")
        self.new_stamp_value_label = QtWidgets.QLabel(self.btn_frame)
        self.new_stamp_value_label.setGeometry(QtCore.QRect(10, 66, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_stamp_value_label.setFont(font)
        self.new_stamp_value_label.setObjectName("new_stamp_value_label")
        self.new_stamp_value_line_edit = QtWidgets.QLineEdit(self.btn_frame)
        self.new_stamp_value_line_edit.setGeometry(QtCore.QRect(10, 90, 191, 21))
        self.new_stamp_value_line_edit.setObjectName("new_stamp_value_line_edit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.new_stamp_name_line_edit, self.new_stamp_value_line_edit)
        MainWindow.setTabOrder(self.new_stamp_value_line_edit, self.add_new_stamp_btn)
        MainWindow.setTabOrder(self.add_new_stamp_btn, self.rmv_selected_btn)
        MainWindow.setTabOrder(self.rmv_selected_btn, self.save_changes_btn)
        MainWindow.setTabOrder(self.save_changes_btn, self.sp_1kg)
        MainWindow.setTabOrder(self.sp_1kg, self.sp_2kg)
        MainWindow.setTabOrder(self.sp_2kg, self.mp_1kg)
        MainWindow.setTabOrder(self.mp_1kg, self.mp_2kg)
        MainWindow.setTabOrder(self.mp_2kg, self.mp_5kg)
        MainWindow.setTabOrder(self.mp_5kg, self.mp_10kg)
        MainWindow.setTabOrder(self.mp_10kg, self.mp_20kg)
        MainWindow.setTabOrder(self.mp_20kg, self.calc_stamps_button)
        MainWindow.setTabOrder(self.calc_stamps_button, self.result_list)
        MainWindow.setTabOrder(self.result_list, self.current_stamps_list)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stamp Calculator"))
        self.small_parcel_label.setText(_translate("MainWindow", "Small Parcel"))
        self.sp_1kg.setText(_translate("MainWindow", "1kg"))
        self.sp_2kg.setText(_translate("MainWindow", "2kg"))
        self.mp_2kg.setText(_translate("MainWindow", "2kg"))
        self.mp_1kg.setText(_translate("MainWindow", "1kg"))
        self.meidum_parcel_label.setText(_translate("MainWindow", "Medium Parcel"))
        self.mp_5kg.setText(_translate("MainWindow", "5kg"))
        self.mp_20kg.setText(_translate("MainWindow", "20kg"))
        self.mp_10kg.setText(_translate("MainWindow", "10kg"))
        self.calc_stamps_button.setText(_translate("MainWindow", "Calculate Postage"))
        self.result_label.setText(_translate("MainWindow", "Postage"))
        self.current_stamps_label.setText(_translate("MainWindow", "Stock"))
        self.tools_label.setText(_translate("MainWindow", "Tools"))
        self.rmv_selected_btn.setText(_translate("MainWindow", "Remove selected stamp"))
        self.add_new_stamp_btn.setText(_translate("MainWindow", "Add Stamp"))
        self.new_stamp_name_label.setText(_translate("MainWindow", "New stamp name:"))
        self.save_changes_btn.setText(_translate("MainWindow", "SAVE CHANGES"))
        self.new_stamp_value_label.setText(_translate("MainWindow", "New stamp value (pence):"))

