# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stamp_calc.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 377)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.small_parcel_label = QtWidgets.QLabel(self.centralwidget)
        self.small_parcel_label.setGeometry(QtCore.QRect(20, 10, 61, 31))
        self.small_parcel_label.setObjectName("small_parcel_label")
        self.sp_1kg = QtWidgets.QRadioButton(self.centralwidget)
        self.sp_1kg.setGeometry(QtCore.QRect(50, 50, 82, 17))
        self.sp_1kg.setObjectName("sp_1kg")
        self.sp_2kg = QtWidgets.QRadioButton(self.centralwidget)
        self.sp_2kg.setGeometry(QtCore.QRect(50, 80, 82, 17))
        self.sp_2kg.setObjectName("sp_2kg")
        self.mp_2kg = QtWidgets.QRadioButton(self.centralwidget)
        self.mp_2kg.setGeometry(QtCore.QRect(50, 170, 82, 17))
        self.mp_2kg.setObjectName("mp_2kg")
        self.mp_1kg = QtWidgets.QRadioButton(self.centralwidget)
        self.mp_1kg.setGeometry(QtCore.QRect(50, 140, 82, 17))
        self.mp_1kg.setObjectName("mp_1kg")
        self.meidum_parcel_label = QtWidgets.QLabel(self.centralwidget)
        self.meidum_parcel_label.setGeometry(QtCore.QRect(20, 100, 71, 31))
        self.meidum_parcel_label.setObjectName("meidum_parcel_label")
        self.mp_5kg = QtWidgets.QRadioButton(self.centralwidget)
        self.mp_5kg.setGeometry(QtCore.QRect(50, 200, 82, 17))
        self.mp_5kg.setObjectName("mp_5kg")
        self.mp_20kg = QtWidgets.QRadioButton(self.centralwidget)
        self.mp_20kg.setGeometry(QtCore.QRect(50, 260, 82, 17))
        self.mp_20kg.setObjectName("mp_20kg")
        self.mp_10kg = QtWidgets.QRadioButton(self.centralwidget)
        self.mp_10kg.setGeometry(QtCore.QRect(50, 230, 82, 17))
        self.mp_10kg.setObjectName("mp_10kg")
        self.calc_stamps_button = QtWidgets.QToolButton(self.centralwidget)
        self.calc_stamps_button.setGeometry(QtCore.QRect(20, 290, 111, 41))
        self.calc_stamps_button.setObjectName("calc_stamps_button")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(170, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.result_label.setFont(font)
        self.result_label.setObjectName("result_label")
        self.vertical_line_1 = QtWidgets.QFrame(self.centralwidget)
        self.vertical_line_1.setGeometry(QtCore.QRect(140, 0, 20, 341))
        self.vertical_line_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.vertical_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vertical_line_1.setObjectName("vertical_line_1")
        self.vertical_line_2 = QtWidgets.QFrame(self.centralwidget)
        self.vertical_line_2.setGeometry(QtCore.QRect(400, 0, 20, 341))
        self.vertical_line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.vertical_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vertical_line_2.setObjectName("vertical_line_2")
        self.current_stamps_label = QtWidgets.QLabel(self.centralwidget)
        self.current_stamps_label.setGeometry(QtCore.QRect(430, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.current_stamps_label.setFont(font)
        self.current_stamps_label.setObjectName("current_stamps_label")
        self.result_list = QtWidgets.QListWidget(self.centralwidget)
        self.result_list.setGeometry(QtCore.QRect(170, 50, 221, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.result_list.setFont(font)
        self.result_list.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.result_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.result_list.setObjectName("result_list")
        self.current_stamps_list = QtWidgets.QListWidget(self.centralwidget)
        self.current_stamps_list.setGeometry(QtCore.QRect(430, 50, 221, 291))
        self.current_stamps_list.setProperty("showDropIndicator", False)
        self.current_stamps_list.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.current_stamps_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.current_stamps_list.setProperty("isWrapping", False)
        self.current_stamps_list.setWordWrap(True)
        self.current_stamps_list.setObjectName("current_stamps_list")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stamp Calculator"))
        self.small_parcel_label.setText(_translate("MainWindow", "Small Parcel"))
        self.sp_1kg.setText(_translate("MainWindow", "1kg"))
        self.sp_2kg.setText(_translate("MainWindow", "2kg"))
        self.mp_2kg.setText(_translate("MainWindow", "2kg"))
        self.mp_1kg.setText(_translate("MainWindow", "1kg"))
        self.meidum_parcel_label.setText(_translate("MainWindow", "Medium Parcel"))
        self.mp_5kg.setText(_translate("MainWindow", "5kg"))
        self.mp_20kg.setText(_translate("MainWindow", "20kg"))
        self.mp_10kg.setText(_translate("MainWindow", "10kg"))
        self.calc_stamps_button.setText(_translate("MainWindow", "Calculate Stamps"))
        self.result_label.setText(_translate("MainWindow", "Result:"))
        self.current_stamps_label.setText(_translate("MainWindow", "Current stamps:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

